package org.example;

//Record is a class that has by default:
// 1. all fields are private final
// 2. getters and setters (getName() -> Name())
// 3. toString, equals&hashCode
// 4. all args constructor
public record Person(String name, int age) {

    // if we write constructor without (), then we simply extend autogenerated "all args constructor"
    public Person {
        System.out.println("Autogenerated constructor with extended functionalities.");
    }

    // we can also overload our constructor
    // but as we know, in records all our fields are final, so we simply cannot leave our fields uninitialized
    // this is why we are calling our "all args constructor" and pass it some values (for example as below)
    public Person() {
        this("default name", 0);
        System.out.println("Custom constructor calling autogenerated constructor.");
    }

    // from now on, we can use this record class as a regular class (write some methods etc.)
    public void showPersonInfo() {
        System.out.println(name + " " + age);
    }
}
